
# @name adminLogin
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "senha"
}

###

# @name editorLogin
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "editor@example.com",
    "password": "password"
}

###

# @name userLogin
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "password"
}

###

@tokenAdmin = {{ adminLogin.response.body.token }}
@tokenEditor = {{ editorLogin.response.body.token }}
@tokenUser = {{ userLogin.response.body.token }}

###

GET http://localhost:8000/api/pessoas
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{tokenAdmin}}

###

GET http://localhost:8000/api/pessoas/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{tokenAdmin}}


###
POST http://localhost:8000/api/pessoas
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "pes_nome": "Nara Laiane",
    "pes_data_nascimento": "1942-10-12",
    "pes_sexo": "Masculino",
    "pes_pai": "Pai de Nara Laiane",
    "pes_mae": "Mãe de Nara Laiane"
}


###


PUT http://localhost:8000/api/pessoas/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "pes_nome": "Nara Laiane Oliveira",
    "pes_data_nascimento": "1942-10-12",
    "pes_sexo": "Feminino",
    "pes_pai": "Pai de Nara Laiane Oliveira",
    "pes_mae": "Mãe de Nara Laiane Oliveira"
}


###
DELETE http://localhost:8000/api/pessoas/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{tokenEditor}}

###
POST http://localhost:8000/api/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{tokenAdmin}}

###
# @name uploadFotos
POST http://localhost:8000/api/pessoas/1/fotos
Authorization: Bearer {{tokenAdmin}}
Accept: application/json
Content-Type: multipart/form-data; boundary=---011000010111000001101001

-----011000010111000001101001
Content-Disposition: form-data; name="pes_id"

2
-----011000010111000001101001
Content-Disposition: form-data; name="fotos[]"; filename="foto1.jpeg"
Content-Type: image/jpeg

< ./tests/images/photo1.jpeg
-----011000010111000001101001
Content-Disposition: form-data; name="fotos[]"; filename="foto2.jpeg"
Content-Type: image/jpeg

< ./tests/images/photo2.jpeg
-----011000010111000001101001
Content-Disposition: form-data; name="fotos[]"; filename="foto3.jpeg"
Content-Type: image/jpeg

< ./tests/images/photo3.jpeg
-----011000010111000001101001
Content-Disposition: form-data; name="fotos[]"; filename="foto4.jpeg"
Content-Type: image/jpeg

< ./tests/images/photo4.jpeg
-----011000010111000001101001--

