GET http://localhost:8000/api/pessoas
Content-Type: application/json
Accept: application/json
Authorization: Bearer 6|bJ4Rxbbvn8FZLaDfmg13jz4XuY9g2c0Lt46jqJNAbdb613f7


###
POST http://localhost:8000/api/pessoas
Content-Type: application/json
Accept: application/json

{
    "pes_nome": "João Silva",
    "pes_data_nascimento": "1986-02-08",
    "pes_sexo": "M",
    "pes_pai": "Pai do João da Silva",
    "pes_mae": "Mãe do João da Silva"
}

###
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "senha"
}

###
POST http://localhost:8000/api/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer 4|C7zwb8xRYEtIN8JkO030EqDGanc2WFca56senYNW15a0a0a3

