services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio_storage
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

  app:
    build:
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    depends_on:
      - postgres
      - minio
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: mydatabase
      DB_USERNAME: admin
      DB_PASSWORD: admin
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./laravel:/var/www/html

volumes:
  postgres_data:
  minio_data:
